name: Node.js CI

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publising to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Push
        run: docker build -t ghcr.io/elenamerelo/gofit . && docker push ghcr.io/elenamerelo/gofit
  build:
    needs: login
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v `pwd`:/test -t ghcr.io/elenamerelo/gofit
