name: Node.js CI

on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push
        run: docker build -t elenamerelo/gofit . && docker push elenamerelo/gofit
      - uses: actions/checkout@v2
      - name: Publising to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: Push
        run: docker build -t ghcr.io/elenamerelo/gofit . && docker push ghcr.io/elenamerelo/gofit
  build:
    needs: login
    runs-on: ubuntu-latest
    container: elenamerelo/gofit
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: npm test
